# Generated by Django 3.2.5 on 2021-07-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesteUsuario', '0003_foto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='imagens'),
        ),
    ]
