# Generated by Django 3.2.5 on 2021-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesteUsuario', '0004_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
